<a href="https://colab.research.google.com/github/RajeshRanaGiet/AML-LAB/blob/main/Experiment%206/AML_EXP_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np
alph5a = float(input("Enter the chi square tabulated : "))
m = int(input("Enter the number of rows : "))
matrix = []
print("Enter the data :- ")
for i in range(m):
  temp = [int(x) for x in input(f"Enter for {i+1} rows :- ").split(",")]
  temp.append(sum(temp))
  matrix.append(temp)
matrix.append(np.sum(matrix, axis = 0))
matrix = np.array(matrix)
print(matrix)
n = len(matrix[0])-1
#caluclating the expected value



Enter the chi square tabulated : 3.481
Enter the number of rows : 2
Enter the data :- 
Enter for 1 rows :- 10,5
Enter for 2 rows :- 5,10
[[10  5 15]
 [ 5 10 15]
 [15 15 30]]


In [34]:
tempMatrix = []
tempChi = []
for i in range(m):
  temp1 = []
  for j in range(n):
    temp2 = (matrix[i][-1]*matrix[m][j])/matrix[m][n]
    temp1.append(temp2)
    tempChi.append((temp2-matrix[i][j])**2/temp2)
  tempMatrix.append(temp1)
print("The expected value is :\n",np.array(tempMatrix))
print("The calculated chi square value is :- ", sum(tempChi))
if sum(tempChi < alpha):
  print("The null hypothesis is accepted")
else:
  print("The null hypothesis is rejected")

The expected value is :
 [[7.5 7.5]
 [7.5 7.5]]
The calculated chi square value is :-  3.3333333333333335
The null hypothesis is rejected
